### ISSUE TITLE
複数の地域がSearchにでてこない

### ISSUE THREAD

**Issue by issi** [issi/craigslist-opml-generator#1]
複数の地域がSearchにでてこない、一番最初のソフトでは問題なかったはずなので、Statesの参照構造による弊害か? Feedbinからのexportにも、地域名記載なし(i.e.,Cleveland, Cincinnati, ,Dayton, Philadelphia, e.t.c..)

**Comment by kotashiratsuka** [comment]
fixed 381c9e5
