### ISSUE TITLE
RSS 更新が全くされていない

### ISSUE THREAD

**Issue by issi** [issi/craigslist-opml-generator#3]
RSSの更新があきらかに行われていない。

**Comment by kotashiratsuka** [comment]
先ずは、Feedbinか、Craigslistの問題かどうか切り分けが必要かと

**Comment by issi** [comment]
素のcraiglistのURL:"https://philadelphia.craigslist.org/search/mca?format=rss&query=kawasaki"を直接Feedbinにいれてもfeed not foundになる。

**Comment by issi** [comment]
検索ワードなしだと、うまくいく
https://philadelphia.craigslist.org/search/mca?format=rss

**Comment by issi** [comment]
なので、Craiglist側の問題??

**Comment by kotashiratsuka** [comment]
http://pastebin.com/8BsHNRhd

ちゃんと出力されている

**Comment by issi** [comment]
確かに、Feedbinが、この検索ワードありのRSSに対応してないとか??

https://philadelphia.craigslist.org/search/mca?format=rss&query=kawasaki

Safariで表示できるし

**Comment by issi** [comment]
Feedbinの問題かとおもって、Feedlyでやってみたら、今度は車種がむちゃくちゃになった。
更新は、確認できなかった。

**Comment by issi** [comment]
CraigslistのRSSが死んでる可能性は?

**Comment by issi** [comment]
http://www.tempestblog.com/2014/06/03/craigslist-blocking-feedly-again/
これが、怪しいなCraigslistは、RSSりーだをブロックするらしい

**Comment by kotashiratsuka** [comment]
クラウド型のフィードサービスは諦めて、localで取得するようにするため、新たにbranchを作成

https://github.com/issi/craigslist-opml-generator/tree/lists_only

**Comment by kotashiratsuka** [comment]
1. git clone git@github.com:issi/craigslist-opml-generator.git
2. cd craigslist-opml-generator
3. ./opml_generator.sh > craigslist.opml
4. Raunch Reeder on MacOS X
5. Menu -> Preferences -> Accounts -> Add Account -> RSS (local no syncing) and if other settings more
6. Menu -> Subscriptions -> Import from OPML..
7. Select a file Dialog -> craigslist.opml
8. dane

**Comment by kotashiratsuka** [comment]
グループ分けにも対応した
![screenshot-2016-07-28](https://cloud.githubusercontent.com/assets/1435951/17185017/2974184e-546a-11e6-8b71-8dc1e05cefea.PNG)
こんな感じ @issi

**Comment by issi** [comment]
Reederでうまくいった

![2016-07-27 21 57 54](https://cloud.githubusercontent.com/assets/2953076/17198716/79d156a0-5445-11e6-940e-2f7c045678a9.png)

**Comment by issi** [comment]
Mission Complete

**Comment by kotashiratsuka** [comment]
:night_with_stars:

**Comment by issi** [comment]
ありがとう、!!
