### ISSUE TITLE
GitのManualを読む

### ISSUE THREAD

**Issue by kotashiratsuka** [issi/craigslist-opml-generator#7]
WebUIじゃなくてダウンロードしたPDFマニュアルでやってみよう

**Comment by kotashiratsuka** [comment]
@issi mentionのtest

**Comment by issi** [comment]
オンラインのPDF日本語版ある?

**Comment by issi** [comment]
@kotashiratsuka じゃあ英語版?

**Comment by kotashiratsuka** [comment]
ggrks

https://www.google.co.jp/search?client=safari&rls=en&q=git+manual&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=LKeiV7KpO6vf8Ae-1KTwDQ

https://git-scm.com/book/en/v2
https://git-scm.com/book/ja/v2

**Comment by issi** [comment]
これは、PDFじゃなくない?

2016/08/03 22:24$B!"(BKota Shiratsuka notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by issi** [comment]
俺も見つけてた。

2016/08/03 22:24$B!"(BKota Shiratsuka notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by kotashiratsuka** [comment]
化けてる @issi

**Comment by issi** [comment]
文字化け、訂正しておいた、mailから直接日本語返信したから化けてた模様
